# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build FitGuide App

on:
  push:
    branches: [ main ]
    tags: 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build artifacts
      id: Buildapks
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleRelease
    - name: Upload APK
      id: upload_apk
      uses: actions/upload-artifact@v1
      with:
        name: FitGuide
        path: app/build/outputs/apk/release/app-release-unsigned.apk
  release:
    name: Release APK
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: FitGuide
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${​​​​​{​​​​​ secrets.GITHUB_TOKEN }​​​​​}​​​​​
        with:
          tag_name: ${​​​​​{​​​​​ github.ref }​​​​​}​​​​​
          release_name: Release ${​​​​​{​​​​​ github.ref }​​​​​}​​​​​
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${​​​​​{​​​​​ secrets.GITHUB_TOKEN }​​​​​}​​​​​
        with:
          upload_url: ${​​​​​{​​​​​ steps.create_release.outputs.upload_url }​​​​​}​​​​​
          asset_path: FitGuide/app-release-unsigned.apk
          asset_name: FitGuide.apk
          asset_content_type: application/zip
